In [23]:
import pandas as pd
import numpy as np

In [24]:
df = pd.read_csv(r'C:\Users\User\Documents\Retail_ETL_Pipeline\data\raw_data.csv')

In [25]:
df.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender,Churn
0,44605,2023-05-03 21:30:02,Home,177,1,2427,PayPal,31,1.0,John Rivera,31,Female,0
1,44605,2021-05-16 13:57:44,Electronics,174,3,2448,PayPal,31,1.0,John Rivera,31,Female,0
2,44605,2020-07-13 06:16:57,Books,413,1,2345,Credit Card,31,1.0,John Rivera,31,Female,0
3,44605,2023-01-17 13:14:36,Electronics,396,3,937,Cash,31,0.0,John Rivera,31,Female,0
4,44605,2021-05-01 11:29:27,Books,259,4,2598,PayPal,31,1.0,John Rivera,31,Female,0

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  int64
 1   Purchase Date          250000 non-null  str
 2   Product Category       250000 non-null  str
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   Payment Method         250000 non-null  str
 7   Customer Age           250000 non-null  int64
 8   Returns                202618 non-null  float64
 9   Customer Name          250000 non-null  str
 10  Age                    250000 non-null  int64
 11  Gender                 250000 non-null  str
 12  Churn                  250000 non-null  int64
dtypes: float64(1), int64(7), str(5)
memory usage: 24.8 MB

In [27]:
df = df.drop('Churn',axis = 1)

In [28]:
df.describe()

,Customer ID,Product Price,Quantity,Total Purchase Amount,Customer Age,Returns,Age
count,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,202618.000000,250000.000000
mean,25017.632092,254.742724,3.004936,2725.385196,43.798276,0.500824,43.798276
std,14412.515718,141.738104,1.414737,1442.576095,15.364915,0.500001,15.364915
min,1.000000,10.000000,1.000000,100.000000,18.000000,0.000000,18.000000
25%,12590.000000,132.000000,2.000000,1476.000000,30.000000,0.000000,30.000000
50%,25011.000000,255.000000,3.000000,2725.000000,44.000000,1.000000,44.000000
75%,37441.250000,377.000000,4.000000,3975.000000,57.000000,1.000000,57.000000
max,50000.000000,500.000000,5.000000,5350.000000,70.000000,1.000000,70.000000

In [29]:
df.describe(include = 'all')

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender
count,250000.000000,250000,250000,250000.000000,250000.000000,250000.000000,250000,250000.000000,202618.000000,250000,250000.000000,250000
unique,NaN,249728,4,NaN,NaN,NaN,3,NaN,NaN,39878,NaN,2
top,NaN,2021-12-25 13:07:57,Electronics,NaN,NaN,NaN,Credit Card,NaN,NaN,Michael Johnson,NaN,Male
freq,NaN,2,62630,NaN,NaN,NaN,83547,NaN,NaN,119,NaN,125676
mean,25017.632092,NaN,NaN,254.742724,3.004936,2725.385196,NaN,43.798276,0.500824,NaN,43.798276,NaN
std,14412.515718,NaN,NaN,141.738104,1.414737,1442.576095,NaN,15.364915,0.500001,NaN,15.364915,NaN
min,1.000000,NaN,NaN,10.000000,1.000000,100.000000,NaN,18.000000,0.000000,NaN,18.000000,NaN
25%,12590.000000,NaN,NaN,132.000000,2.000000,1476.000000,NaN,30.000000,0.000000,NaN,30.000000,NaN
50%,25011.000000,NaN,NaN,255.000000,3.000000,2725.000000,NaN,44.000000,1.000000,NaN,44.000000,NaN
75%,37441.250000,NaN,NaN,377.000000,4.000000,3975.000000,NaN,57.000000,1.000000,NaN,57.000000,NaN
max,50000.000000,NaN,NaN,500.000000,5.000000,5350.000000,NaN,70.000000,1.000000,NaN,70.000000,NaN

In [30]:
df['Purchase Date'] = df['Purchase Date'].astype('datetime64[ns]')

In [31]:
df.isna().sum()

Customer ID                  0
Purchase Date                0
Product Category             0
Product Price                0
Quantity                     0
Total Purchase Amount        0
Payment Method               0
Customer Age                 0
Returns                  47382
Customer Name                0
Age                          0
Gender                       0
dtype: int64

In [32]:
df.tail()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender
249995,33807,2023-01-24 12:32:18,Home,436,1,3664,Cash,63,0.0,Gabriel Williams,63,Male
249996,20455,2021-06-04 05:45:25,Electronics,233,1,4374,Credit Card,66,1.0,Barry Foster,66,Female
249997,28055,2022-11-10 17:11:57,Electronics,441,5,5296,Cash,63,NaN,Lisa Johnson,63,Female
249998,15023,2021-06-27 14:42:12,Electronics,44,2,2517,Cash,64,1.0,Melissa Fernandez,64,Male
249999,4148,2020-09-07 05:12:19,Home,307,5,3634,Cash,32,0.0,Angela Norton,32,Male

In [33]:
df['Returns'].fillna(df['Returns'].mode()[0])

0         1.0
1         1.0
2         1.0
3         0.0
4         1.0
         ...
249995    0.0
249996    1.0
249997    1.0
249998    1.0
249999    0.0
Name: Returns, Length: 250000, dtype: float64

In [34]:
df['Returns'] = df['Returns'].fillna(0)

In [35]:
df.isna().sum()

Customer ID              0
Purchase Date            0
Product Category         0
Product Price            0
Quantity                 0
Total Purchase Amount    0
Payment Method           0
Customer Age             0
Returns                  0
Customer Name            0
Age                      0
Gender                   0
dtype: int64

In [36]:
print(df.isna().sum().sum())

0

In [37]:
df.dropna()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender
0,44605,2023-05-03 21:30:02,Home,177,1,2427,PayPal,31,1.0,John Rivera,31,Female
1,44605,2021-05-16 13:57:44,Electronics,174,3,2448,PayPal,31,1.0,John Rivera,31,Female
2,44605,2020-07-13 06:16:57,Books,413,1,2345,Credit Card,31,1.0,John Rivera,31,Female
3,44605,2023-01-17 13:14:36,Electronics,396,3,937,Cash,31,0.0,John Rivera,31,Female
4,44605,2021-05-01 11:29:27,Books,259,4,2598,PayPal,31,1.0,John Rivera,31,Female
...,...,...,...,...,...,...,...,...,...,...,...,...
249995,33807,2023-01-24 12:32:18,Home,436,1,3664,Cash,63,0.0,Gabriel Williams,63,Male
249996,20455,2021-06-04 05:45:25,Electronics,233,1,4374,Credit Card,66,1.0,Barry Foster,66,Female
249997,28055,2022-11-10 17:11:57,Electronics,441,5,5296,Cash,63,0.0,Lisa Johnson,63,Female
249998,15023,2021-06-27 14:42:12,Electronics,44,2,2517,Cash,64,1.0,Melissa Fernandez,64,Male
249999,4148,2020-09-07 05:12:19,Home,307,5,3634,Cash,32,0.0,Angela Norton,32,Male

In [18]:
print(df.duplicated().sum())

0

In [19]:
df.drop_duplicates()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender
0,44605,2023-05-03 21:30:02,Home,177,1,2427,PayPal,31,1.0,John Rivera,31,Female
1,44605,2021-05-16 13:57:44,Electronics,174,3,2448,PayPal,31,1.0,John Rivera,31,Female
2,44605,2020-07-13 06:16:57,Books,413,1,2345,Credit Card,31,1.0,John Rivera,31,Female
3,44605,2023-01-17 13:14:36,Electronics,396,3,937,Cash,31,0.0,John Rivera,31,Female
4,44605,2021-05-01 11:29:27,Books,259,4,2598,PayPal,31,1.0,John Rivera,31,Female
...,...,...,...,...,...,...,...,...,...,...,...,...
249995,33807,2023-01-24 12:32:18,Home,436,1,3664,Cash,63,0.0,Gabriel Williams,63,Male
249996,20455,2021-06-04 05:45:25,Electronics,233,1,4374,Credit Card,66,1.0,Barry Foster,66,Female
249997,28055,2022-11-10 17:11:57,Electronics,441,5,5296,Cash,63,0.0,Lisa Johnson,63,Female
249998,15023,2021-06-27 14:42:12,Electronics,44,2,2517,Cash,64,1.0,Melissa Fernandez,64,Male
249999,4148,2020-09-07 05:12:19,Home,307,5,3634,Cash,32,0.0,Angela Norton,32,Male

In [45]:
df.columns = df.columns.str.replace(' ', '_')

In [50]:
print(df.columns.tolist())

['Customer_ID', 'Purchase_Date', 'Product_Category', 'Product_Price', 'Quantity', 'Total_Purchase_Amount', 'Payment_Method', 'Customer_Age', 'Returns', 'Customer_Name', 'Age', 'Gender', 'order_id']

In [51]:
df.head()

,Customer_ID,Purchase_Date,Product_Category,Product_Price,Quantity,Total_Purchase_Amount,Payment_Method,Customer_Age,Returns,Customer_Name,Age,Gender,order_id
0,44605,2023-05-03 21:30:02,Home,177,1,2427,PayPal,31,1.0,John Rivera,31,Female,1
1,44605,2021-05-16 13:57:44,Electronics,174,3,2448,PayPal,31,1.0,John Rivera,31,Female,2
2,44605,2020-07-13 06:16:57,Books,413,1,2345,Credit Card,31,1.0,John Rivera,31,Female,3
3,44605,2023-01-17 13:14:36,Electronics,396,3,937,Cash,31,0.0,John Rivera,31,Female,4
4,44605,2021-05-01 11:29:27,Books,259,4,2598,PayPal,31,1.0,John Rivera,31,Female,5

In [56]:
df['order_id'] = df_order.index + 1

In [57]:
df_customer = df[['Customer_ID','Customer_Name','Customer_Age','Gender',]]
df_order = df[['order_id','Product_Category','Product_Price','Quantity','Customer_ID']]
df_purchase = df[['Purchase_Date','Total_Purchase_Amount','Payment_Method','Returns','order_id','Customer_ID']]

In [59]:
df_customer.duplicated().sum()

np.int64(200339)

In [62]:
df_customer = df_customer.drop_duplicates()

In [63]:
df_customer

        Customer_ID      Customer_Name  Customer_Age  Gender
0             44605        John Rivera            31  Female
5             13738     Lauren Johnson            27  Female
10            33969        Carol Allen            27    Male
17            42650       Curtis Smith            20  Female
30            24053         Jose Green            53    Male
...             ...                ...           ...     ...
249995        33807   Gabriel Williams            63    Male
249996        20455       Barry Foster            66  Female
249997        28055       Lisa Johnson            63  Female
249998        15023  Melissa Fernandez            64    Male
249999         4148      Angela Norton            32    Male

[49661 rows x 4 columns]

In [65]:
df_order.duplicated().sum()

np.int64(0)

In [68]:
df_purchase.duplicated().sum()

np.int64(0)

In [69]:
df_customer.to_csv('customer_data', index = False)

In [70]:
df_purchase.to_csv('purchase_data', index = False)

In [71]:
df_order.to_csv('order_data', index = False)

In [72]:
print(df_order.columns.tolist())
print(df_order.dtypes)

print(df_purchase.columns.tolist())
print(df_purchase.dtypes)

print(df_customer.columns.tolist())
print(df_customer.dtypes)

['order_id', 'Product_Category', 'Product_Price', 'Quantity', 'Customer_ID']
order_id            int64
Product_Category      str
Product_Price       int64
Quantity            int64
Customer_ID         int64
dtype: object
['Purchase_Date', 'Total_Purchase_Amount', 'Payment_Method', 'Returns', 'order_id', 'Customer_ID']
Purchase_Date            datetime64[ns]
Total_Purchase_Amount             int64
Payment_Method                      str
Returns                         float64
order_id                          int64
Customer_ID                       int64
dtype: object
['Customer_ID', 'Customer_Name', 'Customer_Age', 'Gender']
Customer_ID      int64
Customer_Name      str
Customer_Age     int64
Gender             str
dtype: object

In [73]:
from sqlalchemy import create_engine

In [74]:
server = 'localhost'
database = 'retail'

connection = f"mssql+pyodbc://@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server"

engine = create_engine(connection)

df_order.to_sql(
    name = 'order',
    con = engine,
    if_exists = 'replace',
    index = False

)
print("order is stored successfully")
df_customer.to_sql(
    name = 'customer',
    con = engine,
    if_exists = 'replace',
    index = False

)
print("customer is stored successfully")
df_purchase.to_sql(
    name = 'purchase',
    con = engine,
    if_exists = 'replace',
    index = False

)   
print("purchase is stored successfully")

C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages\pandas\io\sql.py:1649: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

order is stored successfully
customer is stored successfully
purchase is stored successfully